export const queryKeys = {
  dashboard: ["dashboard"] as const,
  referenceData: ["reference-data"] as const,
  currentAudience: ["me", "audience"] as const,
  currentPublishedSchedule: ["me", "published-schedule"] as const,
  currentTeacherAvailability: ["me", "teacher-unavailable-slots"] as const,
  constraintProfiles: ["constraint-profiles"] as const,
  scheduleRunsRoot: ["schedule-runs"] as const,
  scheduleRuns: (query: Record<string, unknown> = {}) => ["schedule-runs", "list", query] as const,
  scheduleRun: (id: string) => ["schedule-runs", id] as const,
  scheduleRunComparison: (baseId: string, targetId: string) => [
    "schedule-runs",
    "compare",
    baseId,
    targetId,
  ] as const,
  auditEventsRoot: ["audit-events"] as const,
  auditEvents: (query: Record<string, unknown> = {}) => ["audit-events", query] as const,
  publishedSchedule: ["published-schedule"] as const,
  publishedScheduleNotifications: ["published-schedule", "notifications"] as const,
  scheduleDrafts: ["schedule-drafts"] as const,
  scheduleDraft: (id: string) => ["schedule-drafts", id] as const,
  scheduleDraftComparison: (id: string) => ["schedule-drafts", id, "compare"] as const,
  scheduleDraftSuggestions: (id: string, examTaskId: string) => [
    "schedule-drafts",
    id,
    "assignments",
    examTaskId,
    "suggestions",
  ] as const,
  scheduleJobsRoot: ["schedule-jobs"] as const,
  scheduleJobs: (query: Record<string, unknown> = {}) => ["schedule-jobs", query] as const,
  scheduleJob: (id: string) => ["schedule-jobs", id] as const,
};
