import type { ExamBatchSummary, ScheduleInput } from "./domain.js";

export const demoBatch: ExamBatchSummary = {
  id: "batch-2026-spring-final",
  name: "2026 春季期末考试",
  status: "ready",
  startDate: "2026-07-10",
  endDate: "2026-07-14",
};

export const demoScheduleInput: ScheduleInput = {
  student_groups: [
    { id: "g-cs-2301", name: "计算机 2301", size: 42, department_id: "cs" },
    { id: "g-cs-2302", name: "计算机 2302", size: 39, department_id: "cs" },
    { id: "g-math-2301", name: "数学 2301", size: 36, department_id: "math" },
    { id: "g-ai-2301", name: "人工智能 2301", size: 44, department_id: "cs" },
  ],
  teachers: [
    { id: "t-zhang", name: "张教授", department_id: "cs", unavailable_slot_ids: ["s-002"] },
    { id: "t-li", name: "李老师", department_id: "cs", unavailable_slot_ids: [] },
    { id: "t-wang", name: "王老师", department_id: "math", unavailable_slot_ids: ["s-004"] },
    { id: "t-chen", name: "陈老师", department_id: "cs", unavailable_slot_ids: [] },
    { id: "t-zhao", name: "赵老师", department_id: "math", unavailable_slot_ids: ["s-001"] },
  ],
  courses: [
    { id: "c-data-structures", name: "数据结构", department_id: "cs", exam_type: "written" },
    { id: "c-database", name: "数据库系统", department_id: "cs", exam_type: "computer" },
    { id: "c-ai", name: "人工智能导论", department_id: "cs", exam_type: "written" },
    { id: "c-calculus", name: "高等数学", department_id: "math", exam_type: "written" },
    { id: "c-english", name: "大学英语口语", department_id: "english", exam_type: "oral" },
    { id: "c-os", name: "操作系统", department_id: "cs", exam_type: "computer" },
  ],
  rooms: [
    { id: "r-101", name: "明德楼 101", building_id: "mingde", capacity: 90, room_type: "standard", equipment_tags: ["projector"] },
    { id: "r-201", name: "明德楼 201", building_id: "mingde", capacity: 70, room_type: "standard", equipment_tags: ["projector"] },
    { id: "r-lab-1", name: "实验中心 A301", building_id: "lab-a", capacity: 60, room_type: "computer_lab", equipment_tags: ["lab_pc", "projector"] },
    { id: "r-lab-2", name: "实验中心 A302", building_id: "lab-a", capacity: 55, room_type: "computer_lab", equipment_tags: ["lab_pc", "projector"] },
    { id: "r-lang-1", name: "语言中心 401", building_id: "language", capacity: 48, room_type: "language_lab", equipment_tags: ["audio", "recorder"] },
  ],
  time_slots: [
    { id: "s-001", date: "2026-07-10", start_time: "09:00", end_time: "11:00", period_index: 0 },
    { id: "s-002", date: "2026-07-10", start_time: "14:00", end_time: "16:00", period_index: 1 },
    { id: "s-003", date: "2026-07-11", start_time: "09:00", end_time: "11:00", period_index: 2 },
    { id: "s-004", date: "2026-07-11", start_time: "14:00", end_time: "16:00", period_index: 3 },
    { id: "s-005", date: "2026-07-12", start_time: "09:00", end_time: "11:00", period_index: 4 },
    { id: "s-006", date: "2026-07-12", start_time: "14:00", end_time: "16:00", period_index: 5 },
  ],
  exam_tasks: [
    {
      id: "e-data-structures",
      course_id: "c-data-structures",
      student_group_ids: ["g-cs-2301"],
      expected_count: 42,
      duration_minutes: 120,
      required_room_type: "standard",
      required_equipment_tags: [],
      allowed_slot_ids: ["s-001", "s-002", "s-003"],
      invigilator_count: 1,
    },
    {
      id: "e-database",
      course_id: "c-database",
      student_group_ids: ["g-cs-2302"],
      expected_count: 39,
      duration_minutes: 120,
      required_room_type: "computer_lab",
      required_equipment_tags: ["lab_pc"],
      allowed_slot_ids: ["s-001", "s-003", "s-005"],
      invigilator_count: 1,
    },
    {
      id: "e-ai",
      course_id: "c-ai",
      student_group_ids: ["g-ai-2301"],
      expected_count: 44,
      duration_minutes: 120,
      required_room_type: "standard",
      required_equipment_tags: [],
      allowed_slot_ids: ["s-002", "s-004", "s-006"],
      invigilator_count: 1,
    },
    {
      id: "e-calculus",
      course_id: "c-calculus",
      student_group_ids: ["g-math-2301"],
      expected_count: 36,
      duration_minutes: 120,
      required_room_type: "standard",
      required_equipment_tags: [],
      allowed_slot_ids: ["s-001", "s-004", "s-005"],
      invigilator_count: 1,
    },
    {
      id: "e-english",
      course_id: "c-english",
      student_group_ids: ["g-cs-2301", "g-ai-2301"],
      expected_count: 86,
      duration_minutes: 120,
      required_room_type: "standard",
      required_equipment_tags: [],
      allowed_slot_ids: ["s-005", "s-006"],
      invigilator_count: 2,
    },
    {
      id: "e-os",
      course_id: "c-os",
      student_group_ids: ["g-cs-2301"],
      expected_count: 42,
      duration_minutes: 120,
      required_room_type: "computer_lab",
      required_equipment_tags: ["lab_pc"],
      allowed_slot_ids: ["s-003", "s-004", "s-006"],
      invigilator_count: 1,
    },
  ],
  constraint_profile: {
    hard_rules: [
      "exam_single_room_slot",
      "room_time_unique",
      "student_group_no_overlap",
      "room_capacity",
      "room_requirement",
      "allowed_slot",
      "teacher_unavailable",
      "teacher_time_unique",
    ],
    soft_weights: {
      student_consecutive_exam: 8,
      teacher_workload_balance: 7,
      room_utilization: 3,
      exam_distribution_balance: 5,
    },
    time_limit_seconds: 10,
  },
  fixed_assignments: [],
  reschedule_context: null,
};
