#!/usr/bin/env bash
set -euo pipefail

export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-examforge-e2e-$$}"
export POSTGRES_PORT="${POSTGRES_PORT:-55432}"
export REDIS_PORT="${REDIS_PORT:-56380}"
export SCHEDULER_PORT="${SCHEDULER_PORT:-5800}"
export API_PORT="${API_PORT:-5400}"
export WEB_PORT="${WEB_PORT:-5300}"
export PUBLISHER_HEALTH_PORT="${PUBLISHER_HEALTH_PORT:-5410}"
export WORKER_HEALTH_PORT="${WORKER_HEALTH_PORT:-5411}"
export WORKER_LOCK_DURATION_MS="${WORKER_LOCK_DURATION_MS:-5000}"
export WORKER_STALLED_INTERVAL_MS="${WORKER_STALLED_INTERVAL_MS:-5000}"
export E2E_API_BASE_URL="${E2E_API_BASE_URL:-http://127.0.0.1:${API_PORT}}"
export E2E_WEB_BASE_URL="${E2E_WEB_BASE_URL:-http://127.0.0.1:${WEB_PORT}}"
export E2E_SCHEDULER_BASE_URL="${E2E_SCHEDULER_BASE_URL:-http://127.0.0.1:${SCHEDULER_PORT}}"
export NEXT_PUBLIC_API_BASE_URL="${NEXT_PUBLIC_API_BASE_URL:-$E2E_API_BASE_URL}"
export E2E_ADMIN_PASSWORD="${E2E_ADMIN_PASSWORD:-e2e-admin-password-2026}"
export E2E_OPERATOR_PASSWORD="${E2E_OPERATOR_PASSWORD:-e2e-operator-password-2026}"
export E2E_TEACHER_PASSWORD="${E2E_TEACHER_PASSWORD:-e2e-teacher-password-2026}"
export E2E_STUDENT_PASSWORD="${E2E_STUDENT_PASSWORD:-e2e-student-password-2026}"
export EXAMFORGE_ADMIN_PASSWORD="$E2E_ADMIN_PASSWORD"
export EXAMFORGE_OPERATOR_PASSWORD="$E2E_OPERATOR_PASSWORD"
export EXAMFORGE_TEACHER_PASSWORD="$E2E_TEACHER_PASSWORD"
export EXAMFORGE_STUDENT_PASSWORD="$E2E_STUDENT_PASSWORD"
export EXAMFORGE_TRUSTED_ORIGINS="$E2E_WEB_BASE_URL"
export EXAMFORGE_SESSION_COOKIE_SECURE=false

cleanup() {
  exit_code=$?
  trap - EXIT INT TERM
  if [[ "${KEEP_DEMO_STACK:-0}" == "1" ]]; then
    printf 'Keeping Compose project %s for inspection.\n' "$COMPOSE_PROJECT_NAME"
  else
    docker compose down --volumes --remove-orphans || true
  fi
  exit "$exit_code"
}
trap cleanup EXIT INT TERM

npm run demo:reset
DEMO_API_BASE_URL="$E2E_API_BASE_URL" \
  DEMO_WEB_BASE_URL="$E2E_WEB_BASE_URL" \
  DEMO_SCHEDULER_BASE_URL="$E2E_SCHEDULER_BASE_URL" \
  DEMO_OPERATOR_PASSWORD="$E2E_OPERATOR_PASSWORD" \
  DEMO_RUN_FAULT_DRILLS=1 \
  npm run demo:smoke
E2E_EXTERNAL_SERVICES=1 npx playwright test
